### ISSUE TITLE
bind `date | date` into variable.

### ISSUE THREAD

**Issue by eshk12** [misha130/datepicker-ionic2#1]
Hello,
I have Ionic2 application that I chosed to use your repo,
I'm trying to make this kinda thing to work:
<ion-input full="true" [min]="HerdDate" ion-datepicker type="text" [(ngModel)]="HerdDate" value="{{HerdDate | date}}"></ion-input>

HerdDate is `public HerdDate: Date = new Date();`
when I do `{{ HerdDate | date }}` on the template I get `8 Jan, 2017` and I would like to push that results into `HerdDate` how can I do it?
Thanks

BTW ~ There is a way to design the DatePicker?

**Comment by misha130** [comment]
Well, you've discovered a bug that the ngmodel doesn't trigger the onchanges event emitter.

As a work around you may use the ionChanged event so you'll get something like 

<ion-input full="true" [min]="HerdDate" ion-datepicker type="text" [(ngModel)]="HerdDate" (ionChanged)="HerdDate = $event">

I'd also suggest not using the [min] as your model because the minimal value keeps changing.

Besides the normal css the library offers [hclasses] and [dclasses] to add additional classes to the normal ones

**Comment by eshk12** [comment]
Hello,
onEvery change that I do it bind it into HerdDate and I get this results: `Sun Jan 08 2017 15:09:09 GMT+0200`  but how to I pipe/filter it to `8 Jan, 2017`?

**Comment by misha130** [comment]
The datepicker retrieves Date back.
I am just a little confused to what you want to do.
If you really want to do get the string in your Component you may do something like this:
```
import { DatePipe } from '@angular2/common'

private _date:Date = new Date();
public stringDate: string;
public get HerdDate() { return _date };
public set HerdDate(date:Date){ 
 this.stringDate = new DatePipe('en').transform(date);
 this._date = date;
} 
```

Otherwise your `[value]="HerdDate | date"` also worked fine

**Comment by eshk12** [comment]
I have fixed it that way: 
`<ion-item full="true" ion-datepicker type="text" (ionChanged)="date = $event">
      <ion-label stacked>תאריך הגעה:</ion-label>
      <ion-input [(ngModel)]="HerdDate" [value]="date | date"></ion-input>
    </ion-item>
`
ts file:

`public HerdDate: Date;
  public date: Date = new Date();`

by the way where is the file i can edit the stylesheet? and can i change the language to Hebrew(RTL)?

**Comment by eshk12** [comment]
how can i use your TS code in html?

**Comment by jelugbo** [comment]
Hi,
I tried using this module in 2 different ionic2 projects but but gave errors 
Uncaught Error: Unexpected value 'DatePickerModule' imported by the module 'AppModule'

I followed your readme and imported the module by adding the two specified lines lines to my app.module

**Comment by misha130** [comment]
You should do an import 
import { DatePickerModule} from 'datepicker-ionic2'

That should do the trick. Ill close the issue so it won't used for general discussions
