### ISSUE TITLE
How to remove the date,year on top of the page?

### ISSUE THREAD

**Issue by gsaikrishna32** [misha130/datepicker-ionic2#10]
Hi Bro,
        I am trying to remove the following:
    1.submit and ok button.
    2.day,month,year,date at top of the calendar. I wanted to display only calendar UI.
       I  am trying to remove but it is not removing.Hope you had understand my problem.Can you please tell me how to do

**Comment by misha130** [comment]
1.You could hide it with:
```
.datepicker-modal-head, datepicker-modal-head-details{
 display:none; 
}
```
But I don't believe it will look good

2. You may do something like this

```
  @ViewChild(DatePickerDirective) private datepickerDirective:DatePickerDirective;
   public date:Date = new Date();
    constructor(){
            this.datepickerDirective.dateSelected.subscribe(date => {
                this.datepickerDirective.dismiss();
                this.date = date;
             });
    }

```
