### ISSUE TITLE
Problem with ionic 3

### ISSUE THREAD

**Issue by ourarash** [misha130/datepicker-ionic2#15]
The datepicker doesn't work with Ionic 3. I tried with an empty tab project using ionic 3 settings from here:

[https://github.com/driftyco/ionic/blob/master/CHANGELOG.md](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md)

**Comment by misha130** [comment]
Fixed in https://github.com/misha130/datepicker-ionic2/commit/33636d389f4a8e21d450b84582e73159d91100dd
Updated to 2.3.1.
Thanks
