### ISSUE TITLE
cannot bind to value

### ISSUE THREAD

**Issue by vinodhum** [misha130/datepicker-ionic2#18]
I am getting below error any idea what am I doing wrong ?
`ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'value' since it isn't a known property of 'span'. ("g>
  <span ion-datepicker locale="en" (ionChanged)="event($event)"  okText="Ok" cancelText="Cancel" [ERROR ->][value]="localDate"
     clear >
{{localDate | date:'dd-MM-yyyy' }} `

**Comment by misha130** [comment]
It seems the datepicker module isn't in your app's NgModule.
If you are lazy loading then its not in your pages module either.

**Comment by vinodhum** [comment]
yep i am lazy loading, thanx it worked.
