### ISSUE TITLE
Set Min Date, Move to next months and click previous is not working..

### ISSUE THREAD

**Issue by nasums** [misha130/datepicker-ionic2#2]
Set Min & Max Dates
min:new Date(),
max:new Date(new Date().setDate(new Date().getDate()+30)),

Below is the HTML - 
<span ion-datepicker (ionChanged)="eventFromDate($event);" [value]="from" [min]="min" full="true" calendar="true" clear class="ScheduleDate">
        <span>{{from | date:'dd-MM-yyyy' }} </span>
    </span>

Now click on next month button for few times - Move to couple of months, and click back to go previous month, but it will not work.

**Comment by misha130** [comment]
Thanks alot, fixed the issue in latest version 2.2.0

**Comment by nasums** [comment]
Thank you, I got latest version, Its working fine.
