### ISSUE TITLE
please  support zh-CN zh-TW 

### ISSUE THREAD

**Issue by ccgitgit** [misha130/datepicker-ionic2#20]
Nice plugin, please support "zh-CN","zh-TW" for Chinese users. Thank you.

**Comment by misha130** [comment]
If you could provide a list of month names & weekdays for both of them that
will be added

**Comment by ccgitgit** [comment]
```
        'zh-CN': {
            weekdays: ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六'],
            months: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月']
        },
        'zh-TW': {
            weekdays: ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六'],
            months: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月']
        },
```
In this case, zh-CN is totally the same as zh-TW. I think it will be ok that only zh-CN is supported.
What really matters is that limit weekdays by doing arr.splice(0,3) won't work for zh-XX . 
Splice(2,3)  or  xxxStr.replace("星期","") is needed.

**Comment by misha130** [comment]
![image](https://i.gyazo.com/99862b9cfc04ba0587b0bd4664a90660.png)
I am guessing this requires me to translate the numbers as well. 
Is number.toLocaleString('zh-Hans-CN-u-nu-hanidec') appropriate?

**Comment by ccgitgit** [comment]
Number.toLocaleString('zh-Hans-CN-u-nu-hanidec')  is NOT needed.
What your image shows is almost perfect for Chinese users.
P.S  
Set "Monday as the first day" as default for zh-CN is appropriate.
![image](https://user-images.githubusercontent.com/15956861/27004650-3933fed2-4e3f-11e7-8363-d8fca7b12a5b.png)

**Comment by misha130** [comment]
Done, updated to 2.3.5 with support to zh-CN/zn-TW (monday included).

Thanks for the help!
