### ISSUE TITLE
Shown date is always today

### ISSUE THREAD

**Issue by Simon-Laux** [misha130/datepicker-ionic2#22]
The Selected date is allways today and not the value that i defined.
![bildschirmfoto vom 2017-06-28 um 18 07 52](https://user-images.githubusercontent.com/18725968/27647851-eb47ddd2-5c2c-11e7-9a9a-9bff3a50674a.png)

But when i press cancel the right date is flashing up and it closes imediately.

How can i resolve this issue?
I belive it has to behave like in the gif in #9 .

```
export class EditEvent {
  initDate:Date=Date.parse('yesterday -6 days');
  constructor(public navCtrl: NavController, public navParams: NavParams) {

  }

  ionViewDidLoad() {
    console.log('ionViewDidLoad EditEvent id:', this.navParams.get('id'));
  }

  setDate(date: Date){
    console.log(date);
    this.initDate=date;
  }

}
```
```
<ion-content padding>
  <span ion-datepicker
  (ionChanged)="setDate($event);"
  [value] = "initDate"
  [locale] = "'Pages.EditEvent.datepickerLang' | translate"
  [okText] = "'alert.ok' | translate"
  [cancelText] = "'alert.cancel' | translate"
  clear class="ScheduleDate">
		<span>{{initDate | date}} <ion-icon name="clipboard" item-left ></ion-icon> </span>
	</span>
</ion-content>
```

ionic info:
```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.4.2
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by Simon-Laux** [comment]
I want to add that my version of this datepicker is:
`"datepicker-ionic2": "^2.4.0",`
and there is also a display bugg on my ipad -> it stucks on the bottom

**Comment by misha130** [comment]
You are right, fixed the bug and released 2.4.1.
Could you explain whats the problem with the ipad? Maybe a picture?

**Comment by Simon-Laux** [comment]
![image](https://user-images.githubusercontent.com/18725968/27677696-dde019ee-5cb2-11e7-91bb-22fe09aee4f0.png)

**Comment by misha130** [comment]
That is..very weird. Its a normal modal of ionic. The only thing I change is the actual content. 
Not how it is displayed. I'll look in to it. Thanks

**Comment by Simon-Laux** [comment]
I tested a normal modal and it works perfectly.
I noticed that your date picker showed up correctly for a moment, while it was closing. 
So maybe it stucks at the animation??

**Comment by Simon-Laux** [comment]
i tested it in an Ipad Air simulator(IOS 10) and it worked fine.
Maybe it occurs only on my device(Ipad 4 IOS 9).
I will close the issue for now.
Thank you very much for your help.
PS: Could you truncate the Weekdays for German to 2 chars <- 3 char seem a little bit weird for me as a German Guy.

**Comment by misha130** [comment]
I sincerely wish I had an iPad to test.
In 2.4.2 made the deutsch weekdays 2 chars instead of 3.
