### ISSUE TITLE
show "No component factory found for undefined" with apk

### ISSUE THREAD

**Issue by kiko555** [misha130/datepicker-ionic2#23]
I can running with ionic serve fine with 2.3.1 , then  build production successful .
But call the datepicker inner apk , got the "No component factory found for undefined" error?

**Comment by kiko555** [comment]
got the error:
> ERROR Error: Uncaught (in promise): Error: No component factory found for undefined. Did you add it to @NgModule.entryComponents?
Error: No component factory found for undefined. Did you add it to @NgModule.entryComponents?

I had follow your readme to add 

> import { DatePickerModule } from 'datepicker-ionic2';
   imports: [
        IonicModule.forRoot(App),
        DatePickerModule,
    ],

**Comment by misha130** [comment]
I encountered the same problem when testing. 
To solve it I update the angular & ionic to the latest versions based on this https://github.com/ionic-team/ionic-conference-app/blob/master/package.json

**Comment by kiko555** [comment]
try to update the ionic, but still not work with "--prod"
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3 browser 4.1.0 ios 4.3.1
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v8.1.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.3

I try to create a new empty ionic project and then build with --prod again,
but still not working.

**Comment by misha130** [comment]
I can't see this the typescript version so please note its 2.3.4.
I literally had to delete the node modules folder and reinstall them again and it worked.
The problem is not clear at all for me at least. 
I removed everything from the ngmodule and left nothing and it still displayed a problem. It seems some sort of a bug with the compiler. I'll do more research.

Thanks
