### ISSUE TITLE
Can't bind to 'value' since it isn't a known property of 'span'.

### ISSUE THREAD

**Issue by Astacius** [misha130/datepicker-ionic2#24]
I tried to use this calendar but it gives me this error,

> <span ion-datepicker (ionChanged)="setDate($event)" 
  [ERROR ->][value]="localDate" 
  [min]="localDate" 
  full="true" 
"): ng:///AppModule/TrackerPage.html@13:2
Can't bind to 'min' since it isn't a known property of 'span'.

**Comment by misha130** [comment]
Note to add to app module the DatePickerModule

**Comment by Astacius** [comment]
I did it but somehow it wasn't recognized, now it is ok, but I have another problem, calendar is not showing up, when I put
`<span ion-datepicker (ionChanged)="setDate($event);" [value]="localDate" [min]="localDate" full="true" calendar="true" clear class="ScheduleDate">
        <span>{{localDate | date}} <ion-icon name="clipboard" item-left ></ion-icon> </span>
    </span>` 
inside of `<ion-content>` it shows only the small calendar icon and nothing else

**Comment by Astacius** [comment]
can you please help me somehow?

**Comment by misha130** [comment]
<ion-item> <ion-label> Item Label </ion-label> <div item-content
ion-datepicker
(ionChanged)="setDate($event);" [value]="localDate" [min]="localDate"
full="true" calendar="true" clear class="ScheduleDate" > Item Content next
to the label </div> </ion-item>

**Comment by Astacius** [comment]
it is still not showing up, just showing 2 labels and when I click on "Item Content next to the label" it returns error:

> ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'getFullYear' of undefined
TypeError: Cannot read property 'getFullYear' of undefined

**Comment by kumarashu123** [comment]
Can you help me i am getting same error

Can't bind to 'value' since it isn't a known property of 'span'.

**Comment by misha130** [comment]
@Astacius its an error because you didnt set initial value on [value]

**Comment by kumarashu123** [comment]
<ion-item> <ion-label> Item Label </ion-label> <div item-content
                          ion-datepicker
                          [value]="localDate" [min]="localDate"
                          full="true" calendar="true" clear class="ScheduleDate" > Item Content next
                            to the label </div>
                        </ion-item>

This code is giving error as
 Can't bind to 'value' since it isn't a known property of 'span'.

**Comment by moda20** [comment]
Is there anyway of limiting the pickable dates in calendar view, like disable all Mondays ?

**Comment by KKeertikeya** [comment]
I'm having the same issue, and that's after setting the initial value on [value]. What is the type of value supposed to be (string/Date/anything else)?

**Comment by misha130** [comment]
Its supposed to be date.
If you are getting Can't bind to 'value' since it isn't a known property of 'span' its an app module problem though

**Comment by hari-dev** [comment]
I'm still facing this issue while preparing for ios production with the command `ionic cordova prepare ios --prod`

```
typescript error 
            Can't bind to 'value' since it isn't a known property of 'div'. (" <ion-col> <span class="label">Date 
            From</span> <div ion-datepicker [ERROR ->][(value)]="dateFromLocalDate" [localeStrings]="dateLocaleString" 
            [min]="dateFromMinDate" clear> ")

typescript error 
            Can't bind to 'localeStrings' since it isn't a known property of 'div'. (" <span class="label">Date 
            From</span> <div ion-datepicker [(value)]="dateFromLocalDate" [ERROR ->][localeStrings]="dateLocaleString" 
            [min]="dateFromMinDate" clear> <span>{{dateFromLoc")

```

Quick help will be appreciated...
