### ISSUE TITLE
Wrong german shortnames for months (selected date in header)

### ISSUE THREAD

**Issue by aroessler2** [misha130/datepicker-ionic2#25]
The german shortname for selected month has only two letters. So Juni (June) and Juli (July) is the same.
It's nesessary to use min. 3 letters.

But there is enough space to show the full name too (is my preferred solution).

**Comment by misha130** [comment]
I've added [localeStrings] in 2.4.3 which lets the user put in the names they want for the months and weeks.
So you can [localeStrings]=" {
                weekdays: ['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'],
                months: ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni',
                    'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember']
            }"

**Comment by aroessler2** [comment]
Thank you so much for the quick implementation.

Please can you update the documentation too.

thanks
