### ISSUE TITLE
Ok and Cancel button texts are missing

### ISSUE THREAD

**Issue by ourarash** [misha130/datepicker-ionic2#28]
Even with okText and cancelText, the text on the buttons is empty:

` <span ion-datepicker (ionChanged)="onSetDate($event);"  (ionCanceled)="onCancelDate($event);" [value]="localDate" 
                                    [min]="localDate" full="false" calendar="true" class="ScheduleDate" [okText]="Ok"  [cancelText]="Cancel">`

This is with Ionic 3.5

**Comment by ourarash** [comment]
![image](https://user-images.githubusercontent.com/20846105/28177685-7112f5e4-67b0-11e7-9fc4-bdc836ef87c3.png)

**Comment by misha130** [comment]
Its [cancelText]="'Cancel'" [okText]="'Ok'"
Since its [] it expects a variable or a string in quotes.

**Comment by ourarash** [comment]
Yeah my bad, it fixed it.
