### ISSUE TITLE
Click-Event Issue on iOS

### ISSUE THREAD

**Issue by aroessler2** [misha130/datepicker-ionic2#29]
If I add the ion-datepicker directive, like in your example, to a span, the icon has to be touched twice to open the calendar.
The solution for this problem is to use a button or add the attribute "tabbable" (Description: http://technotip.com/5093/tappable-attribute-ionic-2/)

but then I have another problem. The date-selection does not work on every click. With the span and no tabbable attribute its fine.

Can anyone reproduce it?
I used an iPad Air with iOS 10.

**Comment by misha130** [comment]
I release a 2.4.7 version where the directive is opened on a tap event rather than click and all (click) changed to (tap) so this SHOULD work unfortunately I do not own an iPad to test on it.

**Comment by aroessler2** [comment]
Works like a charm! Thanks
