### ISSUE TITLE
How to apply language translator?

### ISSUE THREAD

**Issue by nasums** [misha130/datepicker-ionic2#3]
How to apply language changes for calendar control....

https://github.com/ocombe/ng2-translate

**Comment by misha130** [comment]
Added a new 3 more inputs for this:
`[locale]` - for translating the calendar. Avaliable local is en-US, he-IL, pt-BR, ru-RU

`[okText]` - Text for the ok button

`[cancelText]` - Text for the cancel button

**Comment by nasums** [comment]
Its great to see you are very responsive, is there any way to extend this for more languages...
Could you please add German language as well....

if not lets know how do include other languages during development...

**Comment by misha130** [comment]
Added a german support.

I just dont want to spam the inputs right now with too many options so I'll add languages manually

**Comment by nasums** [comment]
Hello,
Need your help again,

 <ion-item ion-datepicker (ionChanged)="eventFromDate($event);" [value]="from" [min]="search.min" [max]="search.max" full="true"  calendar="true" class="ScheduleDate" [locale]="de">

I dont see german language in my calendar - Days, Months are still in english.

I am using Version :  "datepicker-ionic2": "2.2.9",

Pls let me know if I am missing anything.

**Comment by misha130** [comment]
Its locale="de" or [locale]="'de'"
The [] means it should be a variable

**Comment by Simon-Laux** [comment]
I belive, that we use only 2 letters instead of 3 in german for the weekdays.
(Im german and for me it looks a little bit weird.)
