### ISSUE TITLE
date error while converting IST to ISO 

### ISSUE THREAD

**Issue by kumarashu123** [misha130/datepicker-ionic2#34]
converting 
 Fri Aug 18 2017 00:00:00 GMT+0530 (India Standard Time)
to ISO using toISOString() getting as 
2017-08-17T18:30:00.000Z
which is one day before
can you suggest how to convert in to ISO

**Comment by misha130** [comment]
This is the same result if you try to do a new Date().toISOString() and its midnight.
I really can't fix it unless I decide to return strings.
If anyone has any suggestions I'd love to hear them.

You could just manipulate the date and converting it to ISO with moment format maybe.

**Comment by sebinbenjamin** [comment]
You can try to include the current time instead of 00:00:00.  `new Date().toISOString()` would return the current date in Greenwich. It's just slightly more accurate.

And, maybe the conversion to the local date should be handled separately.
