### ISSUE TITLE
Weekday off by one day

### ISSUE THREAD

**Issue by Askrenteam** [misha130/datepicker-ionic2#35]
![screenshot](https://user-images.githubusercontent.com/23434164/28976150-101ac048-793d-11e7-9074-8f8d9e122fcf.png)
When using a locale with the week starting on monday, the week day in the header is off by one day. As you can see in the screenshot, the day is supposed to be Friday, but Saturday is shown.
The problem doesn't occur with locale 'en-UK', so I'm guessing it has to do with the week starting on monday.

**Comment by misha130** [comment]
Are you sure you are on version 2.5.0? Because I fixed it in #31 (https://github.com/misha130/datepicker-ionic2/commit/2be20ab6874af6f4aa4a09074373a465536552da)

**Comment by misha130** [comment]
Fixed in 2.5.1 https://github.com/misha130/datepicker-ionic2/commit/2c0d0eaed1f55a53f92eb4098b84a4e8dc8cbf35 

Thank you so much for alerting me!

**Comment by Askrenteam** [comment]
Thanks !
