### ISSUE TITLE
move years and months

### ISSUE THREAD

**Issue by jordonezb** [misha130/datepicker-ionic2#36]
Hello a question the module can move the year and the month?
![screenshot_1](https://user-images.githubusercontent.com/7756462/29237121-ee04f6d6-7edc-11e7-99b6-04a4428e666a.png)
thanks!!!

**Comment by misha130** [comment]
Nope, but this is a good suggestion!
Thanks!

**Comment by misha130** [comment]
Added in version 2.6.0 where you can click on the year/month/day and it gives you a list to pick from
