### ISSUE TITLE
Error on localeStrings

### ISSUE THREAD

**Issue by josedejesusjaime** [misha130/datepicker-ionic2#37]
Hi i have an issue when i set the localeStrings. It look as follows:

Cannot read property 5 of undefined at datepickercomponent.getSelectedWeekday. Here is the object i used:

 {
        monday: true,
        weekdays: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo'],
        months: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"]

    }

**Comment by misha130** [comment]
I tested it with this and it worked fine:
```
	<span ion-datepicker
	 (ionChanged)="setDate($event);"
	 [value]="initDate"
	 [disabledDates]="disabledDates"
	 [localeStrings]="{
		monday: true,
		weekdays: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo'],
		months: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']
		}
		"
	 clear
	 class="ScheduleDate">
		<span>{{initDate | date}} <ion-icon name="clipboard" item-left ></ion-icon> </span>
	</span>
```

The error also notes that your weekdays only have 4 items in it. Maybe you just didn't save and refresh?

**Comment by josedejesusjaime** [comment]
It works now. I want to change the calendar view. I try with the calendar property calendar=false and with property binding [calendar]="false", but it doesnt work. I saw the modalOptions property, what are the options for this

**Comment by misha130** [comment]
None, it has been removed since I didn't think people used it.

**Comment by josedejesusjaime** [comment]
There s a version i can use ??

**Comment by misha130** [comment]
2.3.6 I think

**Comment by misha130** [comment]
Added in version 2.6.0 this back
