### ISSUE TITLE
Cannot use with --prod

### ISSUE THREAD

**Issue by vldkrt** [misha130/datepicker-ionic2#38]
All works well, but if I try to deploy on the device with --prod configuration and use the directive, the following error is thrown:

> ERROR Error: Uncaught (in promise): Error: No component factory found for undefined. Did you add it to @NgModule.entryComponents?
> Error: No component factory found for undefined. Did you add it to @NgModule.entryComponents?

**Comment by misha130** [comment]
I tried just now and couldn't reproduce it in the demo project with --prod.
What version of ionic, ionic scripts & datepicker?

Also the error might indicate that you have an import that isnt found.
Maybe write the whole error?

**Comment by vldkrt** [comment]
the library versions are:
 "@angular/core": "4.1.3",    
"datepicker-ionic2": "2.5.1",
    "ionic-angular": "3.6.0",
    "@ionic/app-scripts": "2.1.4",
    "ionic": "3.8.1",
    "typescript": "2.3.4"

I think the libraries are up to date.

The error doesn't show much

> ERROR Error: Uncaught (in promise): Error: No component factory found for undefined. Did you add it to @NgModule.entryComponents?
> Error: No component factory found for undefined. Did you add it to @NgModule.entryComponents?
>     at K (main.js:1)
>     at e.resolveComponentFactory (main.js:1)
>     at e.resolveComponentFactory (main.js:1)
>     at e.resolveComponent (main.js:1)
>     at t._viewInit (main.js:1)
>     at main.js:1
>     at t.invoke (polyfills.js:3)
>     at Object.onInvoke (main.js:1)
>     at t.invoke (polyfills.js:3)
>     at r.run (polyfills.js:3)
>     at K (main.js:1)
>     at e.resolveComponentFactory (main.js:1)
>     at e.resolveComponentFactory (main.js:1)
>     at e.resolveComponent (main.js:1)
>     at t._viewInit (main.js:1)
>     at main.js:1
>     at t.invoke (polyfills.js:3)
>     at Object.onInvoke (main.js:1)
>     at t.invoke (polyfills.js:3)
>     at r.run (polyfills.js:3)
>     at c (polyfills.js:3)
>     at Object.reject (polyfills.js:3)
>     at t._fireError (main.js:1)
>     at t._failed (main.js:1)
>     at main.js:1
>     at t.invoke (polyfills.js:3)
>     at Object.onInvoke (main.js:1)
>     at t.invoke (polyfills.js:3)
>     at r.run (polyfills.js:3)
>     at polyfills.js:3


And the way I used it is:

`import {DatePickerDirective} from 'datepicker-ionic2';`

`providers: [DatePickerDirective]`

```
this.datePickerDirective.open();
this.datePickerDirective.changed.subscribe(date => {
        this.dateChanged(moment(date).valueOf())
    });
```

But even if I try the directive over a button, the same error appears. 
For the development use, it work's fine. Maybe the production minification could scramble something?

**Comment by misha130** [comment]
I still didnt manage to replicate it, but one thing I can say for sure you shouldn't put DatePickerDirective into providers since its directive and not an injectable.

This is how I tried to recreate your code:

```
  @ViewChild(DatePickerDirective) public datepicker: DatePickerDirective;
  public ngOnInit() {
    this.datepicker.open();
    this.datepicker.changed.subscribe(() => console.log('change happened'));
  }
```

The only include you should have is the import in ngModule too.
No providers, nor entryComponents.

**Comment by vldkrt** [comment]
I tried with a new ionic2 project on a android device.

[datePickerTest.zip](https://github.com/misha130/datepicker-ionic2/files/1257741/datePickerTest.zip)

```
npm install
ionic cordova platform add android
ionic cordova run android --prod
```

**Comment by misha130** [comment]
![cmd](https://i.gyazo.com/d1b6f70571bb03bf6f08161cc6f25024.png)
I checked and it works fine.
Maybe npm i -g ionic@latest would help

**Comment by vldkrt** [comment]
I think actual there is an issue with the angular-cli uglify mechanism. If I use --aot it works great.

Thank you for your help. Awesome component BTW.
