### ISSUE TITLE
problem changing years 

### ISSUE THREAD

**Issue by nicoGrepAnswer** [misha130/datepicker-ionic2#40]
Hello, you did a great job with this component thank you. I post this message because I am struggling trying to change the years, there is no way I can modify by clicking on it. Maybe I made a stupid mistake but I will be grateful if you can help me.

Also, is there a way to modify the theme color (primary, secondary color...) ?

![capt](https://user-images.githubusercontent.com/31517661/29937412-b8d050c4-8e85-11e7-8d74-5c285a6c8b66.png)
![capt2](https://user-images.githubusercontent.com/31517661/29937413-bb0082ce-8e85-11e7-9520-4149db87e629.png)

Thanks, Nicolas

**Comment by misha130** [comment]
Well everyone needed this so I added in version 2.6.0 that I just released an option to change year/month/day if you click on them in the header.
Also added a [calendar] option so you can pick whether you want to see the calendar at all or not.

Regarding the css overriding:


```
ionic2-datepicker, ionic2-datepicker .datepicker-wrapper{
background:linear-gradient(135deg, #172446 0%, #2a3c60 26%, #5393ae 61%, #5393ae 66%, #335e88 81%, #336084 100%);
    .datepicker-header{
                           background-color:rgba(0,0,0,0.25)!important;
                           .weekday-header{
                                  background-color:rgba(0,0,0,0.25)!important;
                           }
    }
    .button{
                                          background-color:rgba(0,0,0,0.25)!important;

    }
         .row {
         color:white!important;
         .datepicker-selected{
             color:black;
         }
         .datepicker-current{
             color:#bdbdbd;
         }
     }
}

```

Stuff like this can work
