### ISSUE TITLE
Cancel doesn't work

### ISSUE THREAD

**Issue by ourarash** [misha130/datepicker-ionic2#5]
I'm using this with 
`(ionChanged)="setDate($event);"`

No matter if I click ok or cancel the `setDate` function is called. I need setDate to be called only when OK button is called. Thanks!

**Comment by ourarash** [comment]
It would also help if I could get rid of OK and Cancel button and only clicking on a date would dismiss the calendar.

**Comment by ourarash** [comment]
As a workaround, I manually fixed this function after install in my nod_modules folder:

```
DatePickerComponent.prototype.onCancel = function(e) {
        if (this.date)
            this.selectedDate = this.date || new Date();
        this.callback.emit("Cancel"); //----------> Emit Cancel instead
        // this.callback.emit(this.selectedDate);
        this.viewCtrl.dismiss();
    };;
```

**Comment by dovk** [comment]
I am not reporting on an issue here, just wanted to say thank you for a brilliant job! There were no problems installing, it worked on the first try, and it was not hard to change any functionality to my needs. I also changed the UI to fit in with my design. Once again - thank you very much!

![image](https://cloud.githubusercontent.com/assets/3512316/22619757/4874c85c-eb04-11e6-8ad0-619f039c3636.png)

**Comment by misha130** [comment]
Perhaps there should be no emit at all? 
This is a lil bit confusing if you just set and don't check whether its undefined.

**Comment by misha130** [comment]
The latest commit (https://github.com/misha130/datepicker-ionic2/commit/f766e74ae015d510a24e7eb721e21034d36336b30) fixes this problem with the cancel button by adding an ionCanceled which will be emitted when cancel is clicked. 

On the other issue, I don't really want to clutter the configuration too much unless I really must so I wouldn't be adding the removal of ok/cancel at this point.

**Comment by ourarash** [comment]
index.js is missing in the new version. I get this error:

no such file or directory, open '....\node_modules\datepicker-ionic2\index.js'

**Comment by misha130** [comment]
Check your npm log to see if there are any errors on installation.
I checked on several different projects and it worked fine

**Comment by ourarash** [comment]
Thanks for your reply. Here is the log:

`npm install https://github.com/misha130/datepicker-ionic2 --save
plusone@ C:\Users\ourar\Documents\GitHub\BETA\upfront-client
+-- UNMET PEER DEPENDENCY @angular/common@2.2.1
+-- UNMET PEER DEPENDENCY @angular/core@2.2.1
+-- UNMET PEER DEPENDENCY @angular/forms@2.2.1
`-- datepicker-ionic2@2.2.4  (git+https://github.com/misha130/datepicker-ionic2.git#f766e74ae015d510a24e7eb721e21034d36336b3)
  `-- ionic-angular@2.0.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @ng-bootstrap/ng-bootstrap@1.0.0-alpha.20 requires a peer of @angular/core@^2.3.1 but none was installed.
npm WARN @ng-bootstrap/ng-bootstrap@1.0.0-alpha.20 requires a peer of @angular/common@^2.3.1 but none was installed.
npm WARN @ng-bootstrap/ng-bootstrap@1.0.0-alpha.20 requires a peer of @angular/forms@^2.3.1 but none was installed.`

**Comment by misha130** [comment]
do `npm install datepicker-ionic2` instead
