### ISSUE TITLE
Brilliant!

### ISSUE THREAD

**Issue by dovk** [misha130/datepicker-ionic2#6]
I am not reporting on an issue here, just wanted to say thank you for a brilliant job! There were no problems installing, it worked on the first try, and it was not hard to change any functionality to my needs. I also changed the UI to fit in with my design. Once again - thank you very much!

![image](https://cloud.githubusercontent.com/assets/3512316/22619757/4874c85c-eb04-11e6-8ad0-619f039c3636.png)

**Comment by misha130** [comment]
Hey thanks mate, glad to hear.
And your design looks much better than mine actually, haha but glad you found good use to it.
Heres how it looks for me right now:

Plan to add a time picker in here aswell soon enough
![](https://i.gyazo.com/ed630ded795a4ef92eb0b3a2ad7781d3.png)

**Comment by dovk** [comment]
Hi Misha,
I just noticed you live here too!
I work with another programmer, this is our first Ionic2 app, and we don't have a very rich web development background. There are a number of issues where we could benefit from someone with your knowledge, and I was wondering if you were available for part-time consulting on focused issues. For example building components (such as your Datepicker), or creating application models that exemplify best practices for working with Firebase/AngularFire, Observables, Typescript, and so on.
Please let me know if this could be possible.
Thanks,
Dov




Sent from my iPhone

On 4 Feb 2017, at 18:49, Misha Tarnorutsky <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey thanks mate, glad to hear.
And your design looks much better than mine actually, haha but glad you found good use to it.
Heres how it looks for me right now:

Plan to add a time picker in here aswell soon enough
[https://camo.githubusercontent.com/f91b1d1e7e41fb79a8c832aa5c532986e3fd6aa2/68747470733a2f2f692e6779617a6f2e636f6d2f65643633306465643739356134656639326562306233613261643737383164332e706e67]<https://camo.githubusercontent.com/f91b1d1e7e41fb79a8c832aa5c532986e3fd6aa2/68747470733a2f2f692e6779617a6f2e636f6d2f65643633306465643739356134656639326562306233613261643737383164332e706e67>
