### ISSUE TITLE
Choose a date and click on cancel, you could see the selected date is set.

### ISSUE THREAD

**Issue by nasums** [misha130/datepicker-ionic2#9]
Hello,

Pls fix the issue -
1. First choose a date ex: 2 March, then click Ok. Now you could see control is set with valid date. 
2. Now clickc again choose 10 March, click on Cancel. Now the control should have 2 March as date, but you could see 10 March as date, which is invalid.

**Comment by misha130** [comment]
Hey, thanks for making an issue.
What version are you on?

Because I just checked it and doesn't seem to be a problem.
Plus after issue https://github.com/misha130/datepicker-ionic2/issues/5 there is no data coming back after the cancel.
![](https://i.gyazo.com/6592631f841c16c0eddad553134e63aa.gif)
